name: remote ssh command
# on: [push]
on:
  push:
    branches:
      - main 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify the version of Node.js you are using

      - name: Install PM2 globally
        run: |
          npm install pm2 -g

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }} # 213.165.248.90
          username: ${{ secrets.USERNAME }} # root
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            bash update.sh
